// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="tb_ap_axi_tb_ap_axi,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.781000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=252,HLS_SYN_LUT=942,HLS_VERSION=2023_2}" *)

module tb_ap_axi (
        ap_clk,
        ap_rst_n,
        i_ap_port_rdy,
        i_ap_rd_data_vld,
        i_ap_rd_data,
        o_ap_rd_addr,
        o_ap_rd_addr_ap_vld,
        o_ap_rd_addr_vld,
        o_ap_rd_addr_vld_ap_vld,
        s_axi_PU_rd_AWVALID,
        s_axi_PU_rd_AWREADY,
        s_axi_PU_rd_AWADDR,
        s_axi_PU_rd_WVALID,
        s_axi_PU_rd_WREADY,
        s_axi_PU_rd_WDATA,
        s_axi_PU_rd_WSTRB,
        s_axi_PU_rd_ARVALID,
        s_axi_PU_rd_ARREADY,
        s_axi_PU_rd_ARADDR,
        s_axi_PU_rd_RVALID,
        s_axi_PU_rd_RREADY,
        s_axi_PU_rd_RDATA,
        s_axi_PU_rd_RRESP,
        s_axi_PU_rd_BVALID,
        s_axi_PU_rd_BREADY,
        s_axi_PU_rd_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    C_S_AXI_PU_RD_DATA_WIDTH = 32;
parameter    C_S_AXI_PU_RD_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_PU_RD_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [0:0] i_ap_port_rdy;
input  [0:0] i_ap_rd_data_vld;
input  [7:0] i_ap_rd_data;
output  [31:0] o_ap_rd_addr;
output   o_ap_rd_addr_ap_vld;
output  [0:0] o_ap_rd_addr_vld;
output   o_ap_rd_addr_vld_ap_vld;
input   s_axi_PU_rd_AWVALID;
output   s_axi_PU_rd_AWREADY;
input  [C_S_AXI_PU_RD_ADDR_WIDTH - 1:0] s_axi_PU_rd_AWADDR;
input   s_axi_PU_rd_WVALID;
output   s_axi_PU_rd_WREADY;
input  [C_S_AXI_PU_RD_DATA_WIDTH - 1:0] s_axi_PU_rd_WDATA;
input  [C_S_AXI_PU_RD_WSTRB_WIDTH - 1:0] s_axi_PU_rd_WSTRB;
input   s_axi_PU_rd_ARVALID;
output   s_axi_PU_rd_ARREADY;
input  [C_S_AXI_PU_RD_ADDR_WIDTH - 1:0] s_axi_PU_rd_ARADDR;
output   s_axi_PU_rd_RVALID;
input   s_axi_PU_rd_RREADY;
output  [C_S_AXI_PU_RD_DATA_WIDTH - 1:0] s_axi_PU_rd_RDATA;
output  [1:0] s_axi_PU_rd_RRESP;
output   s_axi_PU_rd_BVALID;
input   s_axi_PU_rd_BREADY;
output  [1:0] s_axi_PU_rd_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] i_pu_rd_addr;
reg    o_pu_rd_data_ap_vld;
reg    o_pu_rd_done_ap_vld;
reg   [31:0] i_pu_rd_addr_read_reg_123;
wire    grp_put_addr_fu_97_ap_start;
wire    grp_put_addr_fu_97_ap_done;
wire    grp_put_addr_fu_97_ap_idle;
wire    grp_put_addr_fu_97_ap_ready;
wire   [31:0] grp_put_addr_fu_97_o_ap_rd_addr;
wire    grp_put_addr_fu_97_o_ap_rd_addr_ap_vld;
wire   [0:0] grp_put_addr_fu_97_o_ap_rd_addr_vld;
wire    grp_put_addr_fu_97_o_ap_rd_addr_vld_ap_vld;
wire    grp_get_data_fu_109_ap_start;
wire    grp_get_data_fu_109_ap_done;
wire    grp_get_data_fu_109_ap_idle;
wire    grp_get_data_fu_109_ap_ready;
wire   [31:0] grp_get_data_fu_109_ap_return;
reg    grp_put_addr_fu_97_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_get_data_fu_109_ap_start_reg;
reg    ap_block_state2_on_subcall_done;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_put_addr_fu_97_ap_start_reg = 1'b0;
#0 grp_get_data_fu_109_ap_start_reg = 1'b0;
end

tb_ap_axi_put_addr grp_put_addr_fu_97(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_put_addr_fu_97_ap_start),
    .ap_done(grp_put_addr_fu_97_ap_done),
    .ap_idle(grp_put_addr_fu_97_ap_idle),
    .ap_ready(grp_put_addr_fu_97_ap_ready),
    .i_ap_port_rdy_val(i_ap_port_rdy),
    .i_pu_rd_addr(i_pu_rd_addr_read_reg_123),
    .o_ap_rd_addr(grp_put_addr_fu_97_o_ap_rd_addr),
    .o_ap_rd_addr_ap_vld(grp_put_addr_fu_97_o_ap_rd_addr_ap_vld),
    .o_ap_rd_addr_vld(grp_put_addr_fu_97_o_ap_rd_addr_vld),
    .o_ap_rd_addr_vld_ap_vld(grp_put_addr_fu_97_o_ap_rd_addr_vld_ap_vld)
);

tb_ap_axi_get_data grp_get_data_fu_109(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_get_data_fu_109_ap_start),
    .ap_done(grp_get_data_fu_109_ap_done),
    .ap_idle(grp_get_data_fu_109_ap_idle),
    .ap_ready(grp_get_data_fu_109_ap_ready),
    .i_ap_rd_data_vld_val(i_ap_rd_data_vld),
    .i_ap_rd_data(i_ap_rd_data),
    .ap_return(grp_get_data_fu_109_ap_return)
);

tb_ap_axi_PU_rd_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_PU_RD_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_PU_RD_DATA_WIDTH ))
PU_rd_s_axi_U(
    .AWVALID(s_axi_PU_rd_AWVALID),
    .AWREADY(s_axi_PU_rd_AWREADY),
    .AWADDR(s_axi_PU_rd_AWADDR),
    .WVALID(s_axi_PU_rd_WVALID),
    .WREADY(s_axi_PU_rd_WREADY),
    .WDATA(s_axi_PU_rd_WDATA),
    .WSTRB(s_axi_PU_rd_WSTRB),
    .ARVALID(s_axi_PU_rd_ARVALID),
    .ARREADY(s_axi_PU_rd_ARREADY),
    .ARADDR(s_axi_PU_rd_ARADDR),
    .RVALID(s_axi_PU_rd_RVALID),
    .RREADY(s_axi_PU_rd_RREADY),
    .RDATA(s_axi_PU_rd_RDATA),
    .RRESP(s_axi_PU_rd_RRESP),
    .BVALID(s_axi_PU_rd_BVALID),
    .BREADY(s_axi_PU_rd_BREADY),
    .BRESP(s_axi_PU_rd_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .i_pu_rd_addr(i_pu_rd_addr),
    .o_pu_rd_data(grp_get_data_fu_109_ap_return),
    .o_pu_rd_data_ap_vld(o_pu_rd_data_ap_vld),
    .o_pu_rd_done(8'd1),
    .o_pu_rd_done_ap_vld(o_pu_rd_done_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_get_data_fu_109_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_get_data_fu_109_ap_start_reg <= 1'b1;
        end else if ((grp_get_data_fu_109_ap_ready == 1'b1)) begin
            grp_get_data_fu_109_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_put_addr_fu_97_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_put_addr_fu_97_ap_start_reg <= 1'b1;
        end else if ((grp_put_addr_fu_97_ap_ready == 1'b1)) begin
            grp_put_addr_fu_97_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        i_pu_rd_addr_read_reg_123 <= i_pu_rd_addr;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
        o_pu_rd_data_ap_vld = 1'b1;
    end else begin
        o_pu_rd_data_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
        o_pu_rd_done_ap_vld = 1'b1;
    end else begin
        o_pu_rd_done_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_get_data_fu_109_ap_done == 1'b0) | (grp_put_addr_fu_97_ap_done == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_get_data_fu_109_ap_start = grp_get_data_fu_109_ap_start_reg;

assign grp_put_addr_fu_97_ap_start = grp_put_addr_fu_97_ap_start_reg;

assign o_ap_rd_addr = grp_put_addr_fu_97_o_ap_rd_addr;

assign o_ap_rd_addr_ap_vld = grp_put_addr_fu_97_o_ap_rd_addr_ap_vld;

assign o_ap_rd_addr_vld = grp_put_addr_fu_97_o_ap_rd_addr_vld;

assign o_ap_rd_addr_vld_ap_vld = grp_put_addr_fu_97_o_ap_rd_addr_vld_ap_vld;

endmodule //tb_ap_axi
